framework:
    secret: '%env(ENV_secret)%'
    session:
        handler_id: null
    php_errors:
        log: true
    cache: null
    translator: { fallbacks: ["%locale%"] }
    templating:
        engines: ['twig', 'php']
parameters:
    env(ENV_secret): ThisTokenIsNotSoSecretChangeIt
