sonata_user:
    security_acl: false
    manager_type: orm

    class:
        user: App\Application\Sonata\UserBundle\Entity\User
        group: App\Application\Sonata\UserBundle\Entity\Group

    impersonating:
        route: sonata_admin_dashboard

#    profile:
#        form:
#            type:                 sonata_user_profile
#            handler:              sonata.user.profile.form.handler.default
#            name:                 sonata_user_profile_form
#            validation_groups:
#                # Defaults:
#                - Profile
#                - Default